# Generated by Django 5.1.4 on 2025-01-07 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_userbook_book'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.CharField(blank=True, max_length=280),
        ),
        migrations.AddField(
            model_name='book',
            name='release_year',
            field=models.IntegerField(blank=True, default=1970),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='title',
            field=models.CharField(blank=True, max_length=280),
        ),
    ]
