# Generated by Django 5.1.4 on 2025-01-07 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_authors_book_release_year_book_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='authors',
            field=models.CharField(max_length=280),
        ),
        migrations.AlterField(
            model_name='book',
            name='release_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='book',
            name='title',
            field=models.CharField(max_length=280),
        ),
    ]
