# Generated by Django 5.1.4 on 2025-01-08 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_book_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='google_book_id',
            field=models.CharField(max_length=280),
        ),
    ]
