# Generated by Django 5.1.4 on 2025-01-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_book_authors_alter_book_google_book_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='image_link',
            field=models.CharField(default='missingbook.jpg', max_length=500),
            preserve_default=False,
        ),
    ]
