# Generated by Django 5.1.4 on 2025-01-15 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_book_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='google_book_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
